/**
 * Safety Intelligence view — the hero screen of the product.
 *
 * Its job is to make one number auditable. A judge should be able to check the
 * arithmetic on screen; a person who cannot read a risk matrix should still
 * understand what to do about it. Four questions, in this order:
 *
 *   1. **How safe is this place?** score, band, confidence, coverage
 *   2. **Why this score?** plain language, generated from the scored values
 *   3. **What's affecting my safety?** the positive and negative movements
 *   4. **What changed?** BEFORE -> the factor that moved -> AFTER
 *
 * Every number on this screen comes from one server response. The client
 * computes nothing, and no explanation is written by hand: the sentences are
 * generated by `backend/app/intelligence/scoring.py` from the same features that
 * produced the score, so the prose cannot drift from the arithmetic.
 */

import { api } from '../core/api.js';
import { el, mount, relativeTime } from '../core/dom.js';
import {
  BAND_TONE, card, dataList, dataRow, disclosure, formatStamp, icon,
  metric, metricGrid, notice, pill, skeletonList, safetyTimeline,
} from '../core/ui.js';
import { store } from '../core/store.js';
import { toast } from '../core/feedback.js';

const BAND_HINT = {
  LOW: 'No strong risk signals for this place and time.',
  MODERATE: 'Some risk signals are present. Stay aware of your surroundings.',
  HIGH: 'Several risk signals are present. Prefer main roads and well-lit areas.',
  CRITICAL: 'Multiple strong risk signals. Avoid being here alone if you can.',
};

const BAND_ACTION = {
  LOW: 'Normal precautions.',
  MODERATE: 'Keep your phone charged and tell someone where you are.',
  HIGH: 'Prefer populated routes, avoid isolated stretches, and start Journey Guard.',
  CRITICAL: 'Move to a populated, well-lit place. SheSafe can share your position and record an incident.',
};

/** How the coverage figure is described. The server owns the ratio; this is wording. */
const COVERAGE_TONE = { GOOD: 'safe', THIN: 'caution', POOR: 'danger' };

/* ------------------------------------------------------------------ data */

export async function loadAssessment({ silent = false, params = null } = {}) {
  const target = document.getElementById('assessment-panel');
  if (target && !silent) mount(target, skeletonList(2, { tall: true }));
  try {
    const response = await api.assess(params);
    store.set({ assessment: response.assessment });
    if (target) renderAssessmentPanel(target, response.assessment, response.location);
    return response.assessment;
  } catch (error) {
    store.set({ assessment: null });
    if (target) {
      mount(target,
        notice('caution', 'No position to score',
          error.message || 'A safety score needs a position. Enable location, or open this screen again once GPS has a fix.'),
        el('div', { class: 'btn-row' },
          el('a', { class: 'btn btn--primary btn--block', href: '#/home' }, icon('target'), 'Back to dashboard'),
          el('a', { class: 'btn btn--quiet btn--block', href: '#/places' }, icon('hospital'), 'Find safe places')));
    }
    return null;
  }
}

export async function renderAssessment() {
  await loadAssessment();
  await renderEngineInfo();
}

/* ---------------------------------------------------------------- render */

export function renderAssessmentPanel(target, assessment, position) {
  if (!assessment) {
    mount(target, notice('caution', 'No assessment available', 'SheSafe could not produce a score here. It will not invent one.'));
    return;
  }

  mount(target,
    scoreHero(assessment, position),
    whyThisScore(assessment),
    whatsAffectingMe(assessment),
    whatChanged(assessment),
    provenanceCard(assessment),
    notice('info', 'This is a rule set, not a trained model',
      'SheSafe scores risk with transparent weighted rules. No machine-learning model has been trained on crime data, '
      + 'so no accuracy figure is claimed anywhere in this product.'));
}

/* ------------------------------------------------------ 1. the score ---- */

function scoreHero(assessment, position) {
  const tone = BAND_TONE[assessment.band] || 'neutral';
  const coverage = assessment.coverage || {};
  const coverageTone = COVERAGE_TONE[coverage.label] || 'danger';

  return el('section', { class: 'card card--hero', id: 'assessment-hero' },
    el('div', { class: 'card__head' },
      el('div', {},
        el('h2', { class: 'card__title' }, 'How safe is this place?'),
        el('p', { class: 'card__hint' },
          `${assessment.model || 'Rule-based estimate'} · ${position ? `${position.lat.toFixed(4)}, ${position.lng.toFixed(4)}` : 'no position'}`)),
      pill(assessment.band, tone)),

    el('div', { class: 'row score-row' },
      scoreDial(assessment.safetyScore, assessment.band),
      el('div', { class: 'stack stack--tight grow' },
        metricGrid([
          metric('Safety', `${assessment.safetyScore}/100`, { tone }),
          metric('Risk', assessment.riskScore),
          metric('Confidence', `${Math.round(assessment.confidence * 100)}%`),
          metric('Data coverage', coverage.label || '—', { tone: coverageTone }),
        ]),
        el('p', { class: 'small' }, assessment.confidenceLabel || ''),
        position ? el('p', { class: 'mono' }, `${position.lat.toFixed(5)}, ${position.lng.toFixed(5)}`) : null)),

    el('p', { class: 'hero-verdict' },
      el('strong', {}, `${assessment.band} risk`),
      ` — ${BAND_HINT[assessment.band] || ''}`),
    el('p', { class: 'small' }, BAND_ACTION[assessment.band] || ''),

    coverage.note
      ? notice(coverageTone, `Data coverage: ${coverage.label || 'unknown'}`, coverage.note)
      : null);
}

/* ------------------------------------------------- 2. why this score ---- */

function whyThisScore(assessment) {
  const caveats = assessment.caveats || [];
  return el('section', { class: 'card', id: 'assessment-why' },
    el('div', { class: 'card__head' },
      el('div', {},
        el('h2', { class: 'card__title' }, 'Why this score?'),
        el('p', { class: 'card__hint' },
          'Written by the engine from the same values that produced the score, so the words cannot disagree with the number.'))),
    el('p', { class: 'prose' }, assessment.plainSummary || 'SheSafe did not return a summary for this assessment.'),
    caveats.length
      ? el('details', { class: 'disclosure' },
          el('summary', {}, `What this score cannot tell you (${caveats.length})`),
          el('div', { class: 'stack stack--tight' },
            ...caveats.map((caveat) => el('p', { class: 'small' }, caveat))))
      : null);
}

/* ------------------------------------------- 3. what's affecting me ---- */

function whatsAffectingMe(assessment) {
  const ledger = assessment.ledger || { raising: [], lowering: [], fixed: [] };
  const features = assessment.features || [];
  const nothingMoved = !ledger.raising.length && !ledger.lowering.length;

  return el('section', { class: 'card', id: 'assessment-factors' },
    el('div', { class: 'card__head' },
      el('div', {},
        el('h2', { class: 'card__title' }, "What's affecting my safety?"),
        el('p', { class: 'card__hint' },
          'Each factor\'s risk points, and how far it moved from the neutral baseline the engine '
          + 'assumes when it has no data. Weights total 100.'))),

    el('div', { class: 'ledger' },
      ledgerPanel('Raising risk', ledger.raising, 'risk', ledger.raisingTotal),
      ledgerPanel('Lowering risk', ledger.lowering, 'safe', ledger.loweringTotal)),

    nothingMoved
      ? notice('caution', 'No factor moved away from its baseline',
        'Every input that could move, sat exactly on its neutral prior. The score below is '
        + 'therefore close to the engine\'s starting assumption — read the data coverage, not the score.')
      : null,

    (ledger.fixed || []).length
      ? el('details', { class: 'disclosure', id: 'ledger-fixed' },
          el('summary', {},
            `Unchanged — ${ledger.fixed.length} factor(s) contributing points without moving from their prior`),
          el('p', { class: 'small' }, ledger.note),
          el('ul', { class: 'ledger__list' },
            ...ledger.fixed.map((factor) => el('li', { class: 'ledger__row', dataset: { factor: factor.key } },
              el('span', { class: 'ledger__label' }, factor.label),
              el('span', { class: 'ledger__points' }, `${Number(factor.points).toFixed(1)} pts`),
              el('span', { class: 'ledger__reason small' }, factor.reason)))))
      : null,

    el('div', { class: 'section-title' }, 'Every factor, in full'),
    ...features
      .slice()
      .sort((a, b) => (b.points || 0) - (a.points || 0))
      .map(factorRow),
    el('p', { class: 'small' },
      `Weights: ${Object.entries(assessment.weights || {}).map(([k, v]) => `${k} ${v}`).join(' · ')}`));
}

function ledgerPanel(title, rows, tone, total) {
  return el('div', { class: `ledger__panel ledger__panel--${tone}`, dataset: { ledger: tone } },
    el('div', { class: 'ledger__head' },
      el('span', { class: 'ledger__title' }, title),
      el('span', { class: `ledger__total ledger__total--${tone}` },
        `${total >= 0 ? '+' : '−'}${Math.abs(total || 0).toFixed(1)} pts`)),
    rows.length
      ? el('ul', { class: 'ledger__list' },
          ...rows.map((factor) => el('li', { class: 'ledger__row', dataset: { factor: factor.key } },
            el('span', { class: 'ledger__label' }, factor.label,
              factor.observed ? null : el('span', { class: 'small' }, ' — no data')),
            el('span', { class: 'ledger__reason small' }, factor.reason),
            el('span', { class: `ledger__delta ledger__delta--${tone}` },
              `${factor.deltaPoints >= 0 ? '+' : '−'}${Math.abs(factor.deltaPoints).toFixed(1)}`))))
      : el('p', { class: 'small' },
          'No factor moved in this direction. That is a statement about the data SheSafe has, '
          + 'not about the place.'));
}

/* ---------------------------------------------- 4. what changed --------- */

function whatChanged(assessment) {
  // A comparison already run is re-rendered from the store, so a background
  // refresh cannot silently wipe the answer the user is looking at.
  const held = store.get().comparison;
  return el('section', { class: 'card', id: 'assessment-change' },
    el('div', { class: 'card__head' },
      el('div', {},
        el('h2', { class: 'card__title' }, 'What changed?'),
        el('p', { class: 'card__hint' },
          'Change one input, and SheSafe re-scores with the same engine and subtracts. '
          + 'Nothing is estimated, and if the data is too thin to explain the move, it says so.'))),
    changeControls(assessment),
    el('div', { id: 'change-result' }, held ? comparisonCard(held) : null));
}

/**
 * The four things that can legitimately change a safety score.
 *
 * Each option builds a BEFORE and an AFTER from real inputs. `data` is only
 * offered when something has actually been recorded since the last comparison,
 * because otherwise there is genuinely nothing to show.
 */
const CHANGE_OPTIONS = [
  {
    key: 'time',
    label: 'Time of day',
    hint: 'Right now, against the most contrasting hour',
    iconName: 'clock',
    build(assessment) {
      const hour = Number(assessment.context?.hourLocal ?? new Date().getHours());
      const base = { lat: assessment.context.lat, lng: assessment.context.lng };
      // 23:00 is the engine's highest-risk window and 13:00 its lowest. Whichever
      // contrast is available produces the clearest demonstration; neither side is
      // invented, and both are real hours the engine scores.
      const contrast = hour >= 6 && hour <= 18 ? 23 : 13;
      return { dimension: 'time', before: { ...base, hourLocal: hour }, after: { ...base, hourLocal: contrast } };
    },
  },
  {
    key: 'location',
    label: 'Location',
    hint: 'A point roughly 4 km away',
    iconName: 'pin',
    build(assessment) {
      const { lat, lng } = assessment.context;
      // A real second position, not a guess about which direction is riskier.
      const dLat = 0.035;
      const dLng = 0.035 / Math.max(0.2, Math.cos((lat * Math.PI) / 180));
      return {
        dimension: 'location',
        before: { lat, lng },
        after: { lat: Number((lat + dLat).toFixed(5)), lng: Number((lng + dLng).toFixed(5)) },
      };
    },
  },
  {
    key: 'route',
    label: 'Route',
    hint: 'Short daylight walk vs a long unlit one',
    iconName: 'route',
    build(assessment) {
      const { lat, lng } = assessment.context;
      return {
        dimension: 'route',
        before: { lat, lng, route: { durationMin: 8, distanceKm: 0.6 } },
        after: { lat, lng, route: { durationMin: 62, distanceKm: 4.2, tags: { lit: false, water_crossing: true } } },
      };
    },
  },
  {
    key: 'data',
    label: 'Safety data',
    hint: 'The score with recent records removed',
    iconName: 'database',
    build(assessment) {
      const { lat, lng } = assessment.context;
      // Cut off at the epoch: the BEFORE side is every record SheSafe held before
      // the user ever used the product, which is a genuine second evaluation.
      return {
        dimension: 'data',
        before: { lat, lng, excludeSince: '2020-01-01T00:00:00Z' },
        after: { lat, lng },
      };
    },
  },
];

function changeControls(assessment) {
  return el('div', { class: 'chip-group', role: 'group', 'aria-label': 'Choose what to vary' },
    ...CHANGE_OPTIONS.map((option) => el('button', {
      class: 'chip', type: 'button', dataset: { change: option.key },
      'aria-pressed': 'false',
      onclick: (event) => void runComparison(option, assessment, event.currentTarget),
    }, icon(option.iconName), option.label,
    el('span', { class: 'chip__hint' }, option.hint))));
}

async function runComparison(option, assessment, button) {
  const target = document.getElementById('change-result');
  if (!target) return;
  for (const chip of document.querySelectorAll('[data-change]')) {
    chip.setAttribute('aria-pressed', String(chip === button));
  }
  mount(target, skeletonList(1, { tall: true }));
  try {
    const payload = option.build(assessment);
    const response = await api.compareAssessments(payload);
    store.set({ comparison: response.comparison });
    // Re-query after the await: a background refresh may have replaced this panel
    // while the request was in flight, and writing into a detached node would
    // silently discard the answer.
    mount(document.getElementById('change-result') || target, comparisonCard(response.comparison));
  } catch (error) {
    mount(document.getElementById('change-result') || target, notice('caution', 'That comparison could not be made', error.message));
    toast(error.message, 'warning');
  }
}

/** BEFORE -> the factor that moved -> AFTER, with the numbers the server sent. */
export function comparisonCard(comparison) {
  if (!comparison) return notice('caution', 'No comparison available', 'SheSafe will not show a difference it did not compute.');

  if (comparison.limited) {
    return el('div', { class: 'change change--limited' },
      el('div', { class: 'change__stage' }, scoreBlock(comparison.before, 'BEFORE')),
      el('div', { class: 'change__arrow', 'aria-hidden': 'true' }, icon('arrowDown')),
      el('p', { class: 'change__limited' }, comparison.limitedNote || 'Limited safety data available.'),
      el('div', { class: 'change__stage' }, scoreBlock(comparison.after, 'AFTER')));
  }

  const primary = comparison.primaryFactor;
  return el('div', { class: 'change', dataset: { direction: comparison.direction } },
    el('div', { class: 'change__stage' }, scoreBlock(comparison.before, 'BEFORE')),

    el('div', { class: 'change__arrow', 'aria-hidden': 'true' }, icon('arrowDown')),

    primary
      ? el('div', { class: 'change__factor', dataset: { factor: primary.key, direction: primary.direction } },
          el('span', { class: 'change__factor-label' }, primary.label),
          el('span', { class: 'change__factor-reason' }, primary.afterReason),
          el('span', { class: `change__delta change__delta--${primary.direction}` },
            `${primary.riskDelta > 0 ? '+' : '−'}${Math.abs(primary.riskDelta).toFixed(1)} risk pts`),
          el('span', { class: 'small' }, `Previously: ${primary.beforeReason}`))
      : el('p', { class: 'change__none' }, 'No factor moved. The same inputs produced the same score.'),

    el('div', { class: 'change__arrow', 'aria-hidden': 'true' }, icon('arrowDown')),

    el('div', { class: 'change__stage' }, scoreBlock(comparison.after, 'AFTER')),

    el('p', { class: 'change__headline' },
      comparison.headline,
      el('span', { class: `change__direction change__direction--${comparison.direction}` },
        comparison.safetyDelta === 0
          ? 'no change'
          : `${comparison.safetyDelta > 0 ? '+' : '−'}${Math.abs(comparison.safetyDelta)} safety points`)),

    el('p', { class: 'prose small' }, comparison.explanation),

    (comparison.factors || []).length > 1
      ? el('details', { class: 'disclosure' },
          el('summary', {}, `All ${comparison.factors.length} factors that moved`),
          el('ul', { class: 'stack stack--tight' },
            ...comparison.factors.map((factor) => el('li', { class: 'row row--tight' },
              el('span', { class: 'grow small' }, factor.label),
              el('span', { class: `change__delta change__delta--${factor.direction}` },
                `${factor.riskDelta > 0 ? '+' : '−'}${Math.abs(factor.riskDelta).toFixed(1)}`),
              el('span', { class: 'small' }, factor.afterReason)))))
      : null,

    el('p', { class: 'small' }, comparison.basis));
}

function scoreBlock(side, stage) {
  return el('div', { class: 'change__score' },
    el('span', { class: 'change__stage-label' }, stage),
    el('span', { class: 'change__score-value' }, String(side.safetyScore)),
    el('span', { class: 'change__score-unit' }, 'safety / 100'),
    el('span', { class: 'small' }, `${side.band} risk · ${Math.round(side.confidence * 100)}% confidence`));
}

/* ------------------------------------------------------ provenance ------ */

function provenanceCard(assessment) {
  const context = assessment.context || {};
  return el('section', { class: 'card' },
    el('div', { class: 'card__head' },
      el('div', {},
        el('h2', { class: 'card__title' }, 'Where the numbers came from'),
        el('p', { class: 'card__hint' }, 'Every input, labelled as observed or not observed.')),),
    dataList((assessment.provenance || []).map((entry) => dataRow({
      iconName: entry.observed ? 'checkCircle' : 'info',
      title: entry.feature,
      badges: [pill(entry.observed ? 'Observed' : 'Not observed', entry.observed ? 'safe' : 'neutral')],
      meta: `${entry.source}${entry.observations ? ` · n=${entry.observations}` : ''}`,
    }))),
    context.incidentCount != null
      ? el('p', { class: 'small' },
          `Context: ${context.incidentCount} incident(s), ${context.placeCount} place(s) and `
          + `${context.communityReportCount} community report(s) within ${context.radiusKm} km, `
          + `at ${String(context.hourLocal).padStart(2, '0')}:00 local time.`)
      : null);
}

export function scoreDial(safetyScore, band) {
  const tone = BAND_TONE[band] || 'neutral';
  const radius = 52;
  const circumference = 2 * Math.PI * radius;
  const filled = Math.max(0, Math.min(100, Number(safetyScore) || 0));

  const svg = document.createElementNS('http://www.w3.org/2000/svg', 'svg');
  svg.setAttribute('viewBox', '0 0 120 120');
  svg.setAttribute('class', 'score__ring');
  svg.setAttribute('aria-hidden', 'true');

  const track = document.createElementNS('http://www.w3.org/2000/svg', 'circle');
  track.setAttribute('cx', '60'); track.setAttribute('cy', '60'); track.setAttribute('r', String(radius));
  track.setAttribute('class', 'score__track');

  const value = document.createElementNS('http://www.w3.org/2000/svg', 'circle');
  value.setAttribute('cx', '60'); value.setAttribute('cy', '60'); value.setAttribute('r', String(radius));
  value.setAttribute('class', `score__value-ring score__value-ring--${tone}`);
  value.setAttribute('stroke-dasharray', String(circumference));
  value.setAttribute('stroke-dashoffset', String(circumference * (1 - filled / 100)));
  value.setAttribute('transform', 'rotate(-90 60 60)');

  svg.append(track, value);

  return el('div', { class: 'score', id: 'safety-dial', dataset: { band: String(band).toLowerCase() } },
    svg,
    el('div', { class: 'score__inner' },
      el('div', {},
        el('div', { class: 'score__value' }, String(safetyScore)),
        el('div', { class: 'score__unit' }, 'safety / 100'))));
}

function factorRow(feature) {
  const points = Number(feature.points || 0);
  const delta = feature.deltaPoints;
  const ratio = feature.weight ? Math.min(100, Math.round((points / feature.weight) * 100)) : 0;
  const protective = feature.observed && points <= feature.weight * 0.3;

  return el('div', { class: 'factor', dataset: { factor: feature.key } },
    el('span', { class: 'factor__name' }, feature.label,
      feature.observed ? null : el('span', { class: 'small' }, ' — no data')),
    el('span', {
      class: `factor__points ${protective ? 'factor__points--safe' : 'factor__points--risk'}`,
    }, `+${points.toFixed(1)}`),
    el('progress', {
      class: `factor__bar${protective ? ' factor__bar--safe' : ''}`,
      max: '100', value: String(ratio),
      'aria-label': `${feature.label} used ${ratio}% of its ${feature.weight} available points`,
    }),
    el('span', { class: 'factor__why' }, feature.reason),
    delta === null || delta === undefined
      ? el('span', { class: 'small' }, `Up to ${feature.weight} points available · this input is a fixed curve, so no baseline delta is shown.`)
      : el('span', { class: 'small' },
          `Neutral baseline ${Number(feature.baselinePoints).toFixed(1)} → this input moved the score by ${delta >= 0 ? '+' : '−'}${Math.abs(delta).toFixed(1)}.`),
    feature.detail ? el('span', { class: 'small' }, feature.detail) : null,
    el('span', { class: 'factor__provenance' },
      `${feature.provenance}${feature.observed ? ` · n=${feature.observations}` : ' · not observed'}`));
}

let engineInfo = null;

/**
 * The engine card.
 *
 * `model`, the weights and the limitations change only when the deployment
 * changes, so the response is fetched once per page load instead of on every
 * visit. That removes a duplicate request each time a judge navigates back to
 * Safety Intelligence, and it also keeps the wording identical between visits.
 */
export async function renderEngineInfo({ force = false } = {}) {
  const target = document.getElementById('engine-info');
  if (!target) return;
  if (engineInfo && !force) {
    mount(target, engineInfo);
    return;
  }
  try {
    const response = await api.explain();
    const engine = response.engine;
    engineInfo =
      card('How the engine works', {
        hint: 'Published by the server, so this screen cannot drift from the code that scored you.',
        body: [
          el('div', { class: 'stack stack--tight' },
            el('p', { class: 'small' }, `Engine: ${engine.model}`),
            el('p', { class: 'small' }, engine.scoreSemantics),
            el('div', { class: 'btn-row' },
              ...engine.bands.map((band) => el('div', { class: 'metric' },
                el('div', { class: 'metric__label' }, band.label),
                el('div', { class: 'metric__value' }, `${band.min}–${band.max}`))))),
          el('div', { class: 'section-title' }, 'Known limitations'),
          dataList(engine.limitations.map((limit) => dataRow({ iconName: 'alert', title: limit }))),
        ],
      });
    mount(target, engineInfo);
  } catch (error) {
    mount(target, notice('caution', 'Engine details unavailable', error.message));
  }
}

export { formatStamp, relativeTime, disclosure };
